### ISSUE TITLE
Anamorphic de-squeeze

### ISSUE THREAD

**Issue by Rambalac** [Rambalac/GMaster#1]

**Comment by GrimorJander** [comment]
We usually shot with anamorphic adapter.
This adapter get squeeze image and need to be de-esquezed in post in order to look normal .
But for framing is a big big help to see what we get in post in real time. Thats what live de-esqueeze do. 
Most adapter have 2x ratio, 1.33x, 1.5x and 1.75x.
This is how Marcus (mjas) do it in his ios "scopes app":
https://youtu.be/u_ixmLQ3ChM
Another important feature is Vlog color preview. (Like a Lut import fron the app)
It can be do with a curve or slider for contrast, saturation and brightnes...

**Comment by Rambalac** [comment]
Anamorphic desqueese for 1.33, 1.5, 1.75 and 2 is already implemented together with LUTs
